
INSERT INTO onlinewalletuser(USER_ID, USER_NAME, PASSWORD, PHONE_NUMBER, LOGIN_NAME) VALUES(123,'aishwarya', 'aish','9755466971', 'aish');
INSERT INTO onlinewalletuser(USER_ID, USER_NAME, PASSWORD, PHONE_NUMBER, LOGIN_NAME) VALUES(127,'shubham', 'shubh','7986238259', 'shubham');
INSERT INTO onlinewalletuser(USER_ID, USER_NAME, PASSWORD, PHONE_NUMBER, LOGIN_NAME) VALUES(124,'shashwat', 'shash','9755466972', 'shash');
INSERT INTO onlinewalletuser(USER_ID, USER_NAME, PASSWORD, PHONE_NUMBER, LOGIN_NAME) VALUES(125,'sharon', 'sherry','9755466973', 'sharon');
INSERT INTO onlinewalletuser(USER_ID, USER_NAME, PASSWORD, PHONE_NUMBER, LOGIN_NAME) VALUES(126,'sohaib', 'sohaib','9755466974', 'sohaib');


INSERT INTO onlinewalletaccount (ACCOUNT_ID,ACCOUNT_BALANCE, STATUS, USER_ID) VALUES (123456, 500, 'saving', 123);
INSERT INTO onlinewalletaccount (ACCOUNT_ID,ACCOUNT_BALANCE, STATUS, USER_ID) VALUES (123457, 500, 'saving', 124);
INSERT INTO onlinewalletaccount (ACCOUNT_ID,ACCOUNT_BALANCE, STATUS, USER_ID) VALUES (123458, 500, 'saving', 125);
INSERT INTO onlinewalletaccount (ACCOUNT_ID,ACCOUNT_BALANCE, STATUS, USER_ID) VALUES (123459, 500, 'saving', 126);
INSERT INTO onlinewalletaccount (ACCOUNT_ID,ACCOUNT_BALANCE, STATUS, USER_ID) VALUES (123460, 500, 'saving', 127);
 
